/**
 * NIRO
 * Please add description
 *
 * The version of the OpenAPI document: 0.1.0_inProgress
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Milestone { 
    id: number;
    status: string;
    datetime: string;
}

