/**
 * NIRO
 * Please add description
 *
 * The version of the OpenAPI document: 0.1.0_inProgress
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrangeApiStatusValue } from './orangeApiStatusValue';
import { OrangeApiComponent } from './orangeApiComponent';


/**
 * Reflect service or component health. See [Orange Recommendation](https://recommendations.innov.intraorange/designing-orange-api/#status-path)
 */
export interface OrangeApiStatus { 
    status: OrangeApiStatusValue;
    /**
     * Your service internal name.
     */
    name: string;
    /**
     * major.minor.patch see [semver.org](https://semver.org/) or G00R00C00
     */
    version: string;
    /**
     * Each array entry represents a component your service requires (other web service, database, etc) to be fully functional
     */
    components?: Array<OrangeApiComponent>;
}
export namespace OrangeApiStatus {
}


