/**
 * NIRO
 * Please add description
 *
 * The version of the OpenAPI document: 0.1.0_inProgress
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * status ok | ko.  See [Orange Recommendation](https://recommendations.innov.intraorange/designing-orange-api/#status-path)
 */
export type OrangeApiStatusValue = 'ok' | 'ko';

export const OrangeApiStatusValue = {
    Ok: 'ok' as OrangeApiStatusValue,
    Ko: 'ko' as OrangeApiStatusValue
};

