/**
 * NIRO
 * Please add description
 *
 * The version of the OpenAPI document: 0.1.0_inProgress
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * See [Orange recommendation](https://recommendations.innov.intraorange/designing-orange-api/#error-format)
 */
export interface OrangeApiError { 
    /**
     * An integer coding the error type. This is given to caller so he can translate them if required.
     */
    code: number;
    /**
     * A short localized string that describes the error.
     */
    message: string;
    /**
     * (optional) A long localized error description if needed. It can contain precise information about which parameter is missing, or what are the identifier acceptable values.
     */
    description?: string;
    /**
     * (optional) A URL to online documentation that provides more information about the error.
     */
    infoURL?: string;
}

